# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('left_key', models.IntegerField()),
                ('right_key', models.IntegerField()),
                ('level', models.IntegerField()),
                ('parent_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
            ],
        ),
    ]
