# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_node',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
