# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170514_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='left_key',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='right_key',
            field=models.IntegerField(null=True),
        ),
    ]
