# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 00:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170514_0100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menu',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
