# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 00:24
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170514_0315'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menu',
            managers=[
                ('menu_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
