# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20170514_0324'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menu',
            managers=[
            ],
        ),
    ]
