# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menu_menu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_id',
        ),
    ]
